spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/big_event
    username: root
    password: aA010608
  data:
    redis:
      host: localhost
      port: 6379
#mybatis????
mybatis:
  configuration:
    #?????????
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #??????????????
    map-underscore-to-camel-case: true
